name: Merge PR into stage
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.1.0
        if: contains( github.event.pull_request.labels.*.name, 'merged into stage')
        with:
          type: now
          target_branch: 'stage'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
